use std::{env::VarError, str::FromStr as _};

use axum::response::{IntoResponse, Response};
use diesel_async::pooled_connection::PoolError;
use http::{StatusCode, Uri};
use problem_details::ProblemDetails;
use serde::{Deserialize, Serialize};

pub type Result<T> = std::result::Result<T, AppError>;

/// Wire-shape mirror of [`problem_details::ProblemDetails`] for OpenAPI.
///
/// Every error response from the servers serializes to this RFC 7807 shape via
/// [`AppError`]'s `IntoResponse`. This struct exists so OpenAPI specs can
/// reference a concrete schema; nothing actually constructs values of this
/// type at runtime.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ProblemDetailsSchema {
	/// A URI reference identifying the problem type.
	#[serde(rename = "type")]
	#[schema(format = "uri", example = "/errors/resource-not-found")]
	pub type_: String,
	/// Short human-readable summary of the problem.
	pub title: String,
	/// HTTP status code generated by the origin server.
	#[schema(example = 404)]
	pub status: u16,
	/// Human-readable explanation specific to this occurrence.
	pub detail: Option<String>,
}

#[derive(Debug, thiserror::Error, miette::Diagnostic)]
pub enum AppError {
	#[error("{0}")]
	Custom(String),

	#[error("{0}")]
	Problem(Box<ProblemDetails>),

	#[error("not implemented")]
	NotImplemented,

	#[error("environment: {0}")]
	Environment(#[from] VarError),

	#[error("header: {0}")]
	Header(String),

	#[error("version parse error: {0}")]
	VersionParse(Box<node_semver::SemverError>),

	#[error("database: {0}")]
	DatabasePool(#[from] mobc::Error<PoolError>),

	#[error("database: {0}")]
	DatabaseQuery(#[from] diesel::result::Error),

	#[error("render: {0}")]
	Tera(#[from] tera::Error),

	#[error("io: {0}")]
	Io(String),

	#[error("no versions match given range")]
	NoMatchingVersions,

	#[error("version range is not usable")]
	UnusableRange,

	#[error("timesync: {0}")]
	Timesync(#[from] timesimp::ParseError),

	#[error("missing authentication header: {0}")]
	AuthMissingHeader(&'static str),

	#[error("missing authentication certificate")]
	AuthMissingCertificate,

	#[error("invalid certificate format")]
	AuthInvalidCertificate(String),

	#[error("certificate not found or inactive")]
	AuthCertificateNotFound,

	#[error("insufficient permissions: {required} role required")]
	AuthInsufficientPermissions { required: String },

	#[error("authentication failed: {reason}")]
	AuthFailed { reason: String },

	#[error("device is not registered against any server")]
	DeviceHasNoServer,

	#[error("source 'manual' is reserved for operator submissions")]
	SourceManualForbidden,

	#[error("tailnet directory is unavailable")]
	AuthTailnetDirectoryUnavailable,

	#[error("tailnet node lacks the required tag")]
	AuthTailnetNodeNotPermitted,

	#[error("tagged-device callers are only allowed on /public/... routes")]
	TaggedDeviceNotAllowed,

	#[error("another device already claims this tailscale node id")]
	DeviceTailscaleNodeAlreadyClaimed,

	#[error("cannot merge devices: conflict on tailscale identity or server attachment")]
	DeviceMergeConflict,

	#[error("no tailnet identity could be resolved for this request")]
	AuthTailnetIdentityMissing,

	/// Deliberately opaque refusal for bearer-token-gated endpoints: a missing,
	/// malformed, unknown, revoked, and expired token all collapse to this so
	/// the response is not a token-lifecycle oracle. Maps to 401.
	#[error("missing or invalid access token")]
	AuthTokenNotValid,

	/// User-supplied input was syntactically or semantically invalid.
	/// Maps to 400 so callers don't have to chase a generic 500.
	#[error("invalid request: {0}")]
	BadRequest(String),

	/// Resource conflict — e.g. attempting to import a ticket whose
	/// canonical URL already belongs to a different server id. Maps
	/// to 409.
	#[error("conflict: {0}")]
	Conflict(String),

	/// Deliberately opaque failure for the public enrollment endpoints. Every
	/// pre-completion reason (unknown/archived server, invalid/expired/consumed
	/// token, bad/expired/used challenge nonce, bad signature) collapses to this
	/// so the endpoint isn't an existence/lifecycle oracle. The specific reason
	/// is logged server-side, never returned. Maps to 403.
	#[error("enrollment failed")]
	EnrollmentFailed,

	/// Too many requests from a caller (e.g. the enrollment endpoints'
	/// per-IP / per-server rate limit). Maps to 429.
	#[error("rate limit exceeded")]
	RateLimited,

	/// A dependency Canopy proxies to failed or is not configured — e.g. the
	/// cross-account STS `AssumeRole` for backup-credentials issuance, or
	/// reading a repo-password k8s Secret for `/backup-target`. Maps to 502.
	/// The message is a generic, caller-safe summary; the underlying detail
	/// (which can name roles/buckets/secrets) is logged server-side only.
	#[error("upstream dependency failed: {0}")]
	Upstream(String),
}

impl AppError {
	pub fn custom(err: impl ToString) -> Self {
		Self::Custom(err.to_string())
	}
}

impl From<std::io::Error> for AppError {
	fn from(err: std::io::Error) -> Self {
		Self::Io(err.to_string())
	}
}

impl From<ProblemDetails> for AppError {
	fn from(err: ProblemDetails) -> Self {
		Self::Problem(Box::new(err))
	}
}

impl From<node_semver::SemverError> for AppError {
	fn from(err: node_semver::SemverError) -> Self {
		Self::VersionParse(Box::new(err))
	}
}

impl IntoResponse for AppError {
	fn into_response(self) -> Response {
		let status = self.to_http_status();
		let problem = self.to_problem_details();
		let mut res = problem.into_response();
		*res.status_mut() = status;
		res
	}
}

impl Clone for AppError {
	fn clone(&self) -> Self {
		Self::Problem(Box::new(self.to_problem_details()))
	}
}

impl AppError {
	fn to_http_status(&self) -> StatusCode {
		match self {
			Self::NotImplemented => StatusCode::NOT_IMPLEMENTED,
			Self::NoMatchingVersions => StatusCode::NOT_FOUND,
			Self::UnusableRange => StatusCode::BAD_REQUEST,
			Self::DatabaseQuery(diesel::result::Error::NotFound) => StatusCode::NOT_FOUND,
			Self::AuthMissingHeader(_) => StatusCode::UNAUTHORIZED,
			Self::AuthMissingCertificate => StatusCode::UNAUTHORIZED,
			Self::AuthInvalidCertificate(_) => StatusCode::BAD_REQUEST,
			Self::AuthCertificateNotFound => StatusCode::UNAUTHORIZED,
			Self::AuthInsufficientPermissions { .. } => StatusCode::FORBIDDEN,
			Self::AuthFailed { .. } => StatusCode::UNAUTHORIZED,
			Self::DeviceHasNoServer => StatusCode::PRECONDITION_FAILED,
			Self::SourceManualForbidden => StatusCode::BAD_REQUEST,
			Self::AuthTailnetDirectoryUnavailable => StatusCode::SERVICE_UNAVAILABLE,
			Self::AuthTailnetNodeNotPermitted => StatusCode::FORBIDDEN,
			Self::TaggedDeviceNotAllowed => StatusCode::FORBIDDEN,
			Self::DeviceTailscaleNodeAlreadyClaimed => StatusCode::CONFLICT,
			Self::DeviceMergeConflict => StatusCode::CONFLICT,
			Self::AuthTailnetIdentityMissing => StatusCode::UNAUTHORIZED,
			Self::AuthTokenNotValid => StatusCode::UNAUTHORIZED,
			Self::BadRequest(_) => StatusCode::BAD_REQUEST,
			Self::Conflict(_) => StatusCode::CONFLICT,
			Self::EnrollmentFailed => StatusCode::FORBIDDEN,
			Self::RateLimited => StatusCode::TOO_MANY_REQUESTS,
			Self::Upstream(_) => StatusCode::BAD_GATEWAY,
			_ => StatusCode::INTERNAL_SERVER_ERROR,
		}
	}

	fn to_problem_details(&self) -> ProblemDetails {
		if let Self::Problem(problem) = self {
			return *problem.clone();
		}

		let status = self.to_http_status();
		ProblemDetails::new()
			.with_status(status)
			.with_title(self.to_string())
			.with_detail(format!("{self:?}"))
			.with_type(
				Uri::from_str(&format!(
					"/errors/{slug}",
					slug = match self {
						Self::Custom(_) => "other",
						Self::NotImplemented => "not-implemented",
						Self::Environment(_) => "environment",
						Self::Header(_) => "header",
						Self::VersionParse(_) => "version-parse",
						Self::DatabasePool(_) => "database",
						Self::DatabaseQuery(diesel::result::Error::NotFound) =>
							"resource-not-found",
						Self::DatabaseQuery(_) => "database",
						Self::Tera(_) => "render",
						Self::Io(_) => "io",
						Self::NoMatchingVersions => "no-matching-versions",
						Self::UnusableRange => "unusable-range",
						Self::Timesync(_) => "timesync",
						Self::AuthMissingHeader(_) => "auth-missing-header",
						Self::AuthMissingCertificate => "auth-missing-certificate",
						Self::AuthInvalidCertificate(_) => "auth-invalid-certificate",
						Self::AuthCertificateNotFound => "auth-certificate-not-found",
						Self::AuthInsufficientPermissions { .. } => "auth-insufficient-permissions",
						Self::AuthFailed { .. } => "auth-failed",
						Self::DeviceHasNoServer => "device-has-no-server",
						Self::SourceManualForbidden => "source-manual-forbidden",
						Self::AuthTailnetDirectoryUnavailable =>
							"auth-tailnet-directory-unavailable",
						Self::AuthTailnetNodeNotPermitted => "auth-tailnet-node-not-permitted",
						Self::TaggedDeviceNotAllowed => "tagged-device-not-allowed",
						Self::DeviceTailscaleNodeAlreadyClaimed =>
							"device-tailscale-node-already-claimed",
						Self::DeviceMergeConflict => "device-merge-conflict",
						Self::AuthTailnetIdentityMissing => "auth-tailnet-identity-missing",
						Self::AuthTokenNotValid => "auth-token-not-valid",
						Self::BadRequest(_) => "bad-request",
						Self::Conflict(_) => "conflict",
						Self::EnrollmentFailed => "enrollment-failed",
						Self::RateLimited => "rate-limited",
						Self::Upstream(_) => "upstream",
						Self::Problem(_) => unreachable!(),
					}
				))
				.unwrap(),
			)
	}
}

impl Serialize for AppError {
	fn serialize<S>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error>
	where
		S: serde::Serializer,
	{
		self.to_problem_details().serialize(serializer)
	}
}

impl<'de> Deserialize<'de> for AppError {
	fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
	where
		D: serde::Deserializer<'de>,
	{
		let value = ProblemDetails::deserialize(deserializer)?;
		Ok(AppError::Problem(Box::new(value)))
	}
}
