[workspace]
resolver = "3"
members = [
	"crates/commons-errors",
	"crates/commons-servers",
	"crates/commons-tests",
	"crates/commons-types",
	"crates/database",
	"crates/jobs",
	"crates/private-server",
	"crates/public-server",
]

[workspace.dependencies]
axum = "0.8.9"
axum-test = "20.0.0"
clap = "4.6.1"
diesel = "2.3.9"
diesel-async = "0.9.0"
futures = "0.3.32"
http = "1.4.1"
jiff = { version = "0.2.28", features = ["serde"] }
lloggs = "1.4.0"
miette = "7.6.0"
mobc = "0.9.0"
node-semver = "2.2.0"
problem_details = "0.9.0"
pulldown-cmark = { version = "0.13.4", features = ["html"] }
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls", "stream"] }
serde = "1.0.228"
tera = "1.20.1"
timesimp = "1.0.0"
tokio = "1.52.3"
tracing = "0.1.44"
utoipa = { version = "5", features = ["jiff_0_2", "uuid", "axum_extras"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", default-features = false, features = ["axum", "vendored"] }

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[profile.dev.build-override]
opt-level = 0
codegen-units = 1024
debug = false
debug-assertions = false
overflow-checks = false
incremental = false

[profile.release.build-override]
opt-level = 0
codegen-units = 1024
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
