publish = true
tag-name = "v{{version}}"
tag-message = "release: {{version}}"
pre-release-commit-message = "release: {{version}}"
pre-release-hook = ["git", "cliff", "-c", "cliff.toml", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
pre-release-replacements = [
  { file = "README.md", search = "tamanu-meta:v[0-9\\.]+", replace = "tamanu-meta:v{{version}}"},
]
